-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 17:44:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mine_op
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mine_op
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mine_op` DEFAULT CHARACTER SET utf8 ;
USE `mine_op` ;

-- -----------------------------------------------------
-- Table `mine_op`.`pit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`pit` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The material source locations by pit, stage, RL, blast, block, flitch.',
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `pit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`locationop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`locationop` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The material source locations by pit, stage, RL, blast, block, flitch.',
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `pit` INT NOT NULL,
  `stage` VARCHAR(45) NOT NULL,
  `rl` VARCHAR(45) NOT NULL,
  `blast` VARCHAR(45) NULL,
  `block` VARCHAR(45) NULL,
  `flitch` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locationop_pit1_idx` (`pit` ASC) VISIBLE,
  CONSTRAINT `fk_locationop_pit1`
    FOREIGN KEY (`pit`)
    REFERENCES `mine_op`.`pit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`material` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The grade categorization for ore and waste.',
  `name` VARCHAR(45) NOT NULL COMMENT 'Grade bins. ',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`oxidation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`oxidation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`parcel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`parcel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Parcel is a dig block in the open pit setting.',
  `sg` DECIMAL NOT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `location_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `oxidation_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `evaluations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parcel_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_parcel_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_parcel_oxidation1_idx` (`oxidation_id` ASC) VISIBLE,
  CONSTRAINT `fk_parcel_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parcel_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mine_op`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parcel_oxidation1`
    FOREIGN KEY (`oxidation_id`)
    REFERENCES `mine_op`.`oxidation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`stockpile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`stockpile` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The material source locations by pit, stage, RL, blast, block, flitch.',
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ore` TINYINT NOT NULL COMMENT 'is it an ore stockpile or a waste dump?',
  `rom` TINYINT NOT NULL COMMENT 'is the stockpile on the ROM or not?',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`loadhaul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`loadhaul` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The truck counts table.',
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `movementtype` INT NOT NULL DEFAULT 0 COMMENT 'crusher feed, haulage, rehandle, etc.',
  `loads` INT NOT NULL,
  `comments` VARCHAR(45) NULL,
  `bcm` DECIMAL NOT NULL,
  `tonnes` DECIMAL NOT NULL,
  `ounces` DECIMAL NOT NULL,
  `source` INT NOT NULL COMMENT 'Source.',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `destination` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loadhaul_parcel1_idx` (`source` ASC) VISIBLE,
  INDEX `fk_loadhaul_stockpile1_idx` (`destination` ASC) VISIBLE,
  CONSTRAINT `fk_loadhaul_parcel1`
    FOREIGN KEY (`source`)
    REFERENCES `mine_op`.`parcel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loadhaul_stockpile1`
    FOREIGN KEY (`destination`)
    REFERENCES `mine_op`.`stockpile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`grade` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The grades for each parcel (dig block). Many-to-1 because you could be analyzing for multiple metals.\n\nDiluted grade is calculated off of the truck counts (over mining). Do some sites have dilution in the block model?',
  `eval_type` VARCHAR(45) NULL,
  `analyte` VARCHAR(45) NOT NULL,
  `grade` DECIMAL NOT NULL,
  `diluted` DECIMAL NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `parcel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grade_parcel1_idx` (`parcel_id` ASC) VISIBLE,
  CONSTRAINT `fk_grade_parcel1`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `mine_op`.`parcel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `preferred` TINYINT NOT NULL DEFAULT 1,
  `bcm_undiluted` DECIMAL NOT NULL,
  `bcm_diluted` DECIMAL NOT NULL,
  `tonnes_undiluted` DECIMAL NOT NULL,
  `tonnes_diluted` DECIMAL NOT NULL,
  `moisture` DECIMAL NULL,
  `parcel_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_evaluations_parcel1_idx` (`parcel_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluations_parcel1`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `mine_op`.`parcel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`survey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `volume` DECIMAL NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_survey_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`dwnclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`dwnclass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`dwntype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`dwntype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `stand` TINYINT NOT NULL,
  `maintenance` TINYINT NOT NULL,
  `planned` TINYINT NOT NULL,
  `ops` TINYINT NOT NULL,
  `dwnclass_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_dwntype_dwnclass1_idx` (`dwnclass_id` ASC) VISIBLE,
  CONSTRAINT `fk_dwntype_dwnclass1`
    FOREIGN KEY (`dwnclass_id`)
    REFERENCES `mine_op`.`dwnclass` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`plantclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`plantclass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`planttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`planttype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `plantclass_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_planttype_plantclass1_idx` (`plantclass_id` ASC) VISIBLE,
  CONSTRAINT `fk_planttype_plantclass1`
    FOREIGN KEY (`plantclass_id`)
    REFERENCES `mine_op`.`plantclass` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`plant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`plant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `start` DATETIME NOT NULL,
  `retired` DATETIME NULL,
  `planttype_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plant_planttype1_idx` (`planttype_id` ASC) VISIBLE,
  CONSTRAINT `fk_plant_planttype1`
    FOREIGN KEY (`planttype_id`)
    REFERENCES `mine_op`.`planttype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`downtime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`downtime` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `usable` TINYINT NOT NULL,
  `dwntype_id` INT NOT NULL,
  `location_id` INT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `plant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_downtime_dwntype1_idx` (`dwntype_id` ASC) VISIBLE,
  INDEX `fk_downtime_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_downtime_plant1_idx` (`plant_id` ASC) VISIBLE,
  CONSTRAINT `fk_downtime_dwntype1`
    FOREIGN KEY (`dwntype_id`)
    REFERENCES `mine_op`.`dwntype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_downtime_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_downtime_plant1`
    FOREIGN KEY (`plant_id`)
    REFERENCES `mine_op`.`plant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`drilling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`drilling` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Do we need to add a depletion id?',
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `hole_number` INT NOT NULL,
  `hole_length` DECIMAL NOT NULL,
  `hole_diameter` DECIMAL NOT NULL,
  `azimuth` INT NOT NULL,
  `dip` INT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comment` VARCHAR(45) NULL,
  `parcel_id` INT NULL,
  `redrill` TINYINT NOT NULL DEFAULT 0,
  `drilling_col` VARCHAR(45) NULL,
  `patternid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_drilling_parcel1_idx` (`parcel_id` ASC) VISIBLE,
  CONSTRAINT `fk_drilling_parcel1`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `mine_op`.`parcel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `employee_number` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mine_op`.`company` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`firingtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`firingtype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`firing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`firing` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Do we need to add a depletion id?',
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `meters_adv` DECIMAL NOT NULL,
  `holes_fired` INT NOT NULL,
  `maters_adv_adj` DECIMAL NOT NULL,
  `tonnes_fired` DECIMAL NOT NULL,
  `bcm_fired` DECIMAL NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comment` VARCHAR(45) NULL,
  `firingtype_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `drilling_id` INT NOT NULL,
  `benchheight` DECIMAL NULL,
  `burden` DECIMAL NULL,
  `spacing` DECIMAL NULL,
  `subdrill` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_firing_firingtype1_idx` (`firingtype_id` ASC) VISIBLE,
  INDEX `fk_firing_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_firing_drilling1_idx` (`drilling_id` ASC) VISIBLE,
  CONSTRAINT `fk_firing_firingtype1`
    FOREIGN KEY (`firingtype_id`)
    REFERENCES `mine_op`.`firingtype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_firing_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_firing_drilling1`
    FOREIGN KEY (`drilling_id`)
    REFERENCES `mine_op`.`drilling` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`activitytype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`activitytype` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Types of activities: load and haul, drilling, blasting.',
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`shiftactivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`shiftactivity` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The truck counts table.',
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comments` VARCHAR(45) NULL,
  `shiftboss` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `pit_id` INT NOT NULL,
  `supervisor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shiftactivity_person1_idx` (`shiftboss` ASC) VISIBLE,
  INDEX `fk_shiftactivity_activity1_idx` (`activity_id` ASC) VISIBLE,
  INDEX `fk_shiftactivity_pit1_idx` (`pit_id` ASC) VISIBLE,
  INDEX `fk_shiftactivity_person2_idx` (`supervisor` ASC) VISIBLE,
  CONSTRAINT `fk_shiftactivity_person1`
    FOREIGN KEY (`shiftboss`)
    REFERENCES `mine_op`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shiftactivity_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mine_op`.`activitytype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shiftactivity_pit1`
    FOREIGN KEY (`pit_id`)
    REFERENCES `mine_op`.`pit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shiftactivity_person2`
    FOREIGN KEY (`supervisor`)
    REFERENCES `mine_op`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`planthour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`planthour` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `starthour` DECIMAL NOT NULL,
  `endhour` DECIMAL NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `plant_id` INT NOT NULL,
  `drilling_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `firing_id` INT NOT NULL,
  `shiftactivity_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_planthour_plant1_idx` (`plant_id` ASC) VISIBLE,
  INDEX `fk_planthour_drilling1_idx` (`drilling_id` ASC) VISIBLE,
  INDEX `fk_planthour_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_planthour_firing1_idx` (`firing_id` ASC) VISIBLE,
  INDEX `fk_planthour_shiftactivity1_idx` (`shiftactivity_id` ASC) VISIBLE,
  CONSTRAINT `fk_planthour_plant1`
    FOREIGN KEY (`plant_id`)
    REFERENCES `mine_op`.`plant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planthour_drilling1`
    FOREIGN KEY (`drilling_id`)
    REFERENCES `mine_op`.`drilling` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planthour_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mine_op`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planthour_firing1`
    FOREIGN KEY (`firing_id`)
    REFERENCES `mine_op`.`firing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planthour_shiftactivity1`
    FOREIGN KEY (`shiftactivity_id`)
    REFERENCES `mine_op`.`shiftactivity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `shift_boss` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mine_op`.`department` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`rolehist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`rolehist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `role_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_rolehist_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_rolehist_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_rolehist_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mine_op`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rolehist_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mine_op`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`consclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`consclass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`constype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`constype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `consclass_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_constype_consclass1_idx` (`consclass_id` ASC) VISIBLE,
  CONSTRAINT `fk_constype_consclass1`
    FOREIGN KEY (`consclass_id`)
    REFERENCES `mine_op`.`consclass` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`consumable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`consumable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `supplier` VARCHAR(45) NULL,
  `explosive` TINYINT NOT NULL,
  `active` TINYINT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `constype_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consumable_constype1_idx` (`constype_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumable_constype1`
    FOREIGN KEY (`constype_id`)
    REFERENCES `mine_op`.`constype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`consfiring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`consfiring` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `consumable_id` INT NOT NULL,
  `firing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consfiring_consumable1_idx` (`consumable_id` ASC) VISIBLE,
  INDEX `fk_consfiring_firing1_idx` (`firing_id` ASC) VISIBLE,
  CONSTRAINT `fk_consfiring_consumable1`
    FOREIGN KEY (`consumable_id`)
    REFERENCES `mine_op`.`consumable` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consfiring_firing1`
    FOREIGN KEY (`firing_id`)
    REFERENCES `mine_op`.`firing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`measure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`measure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `measure_col` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`measfiring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`measfiring` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `measure_id` INT NOT NULL,
  `firing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consmeasure_measure1_idx` (`measure_id` ASC) VISIBLE,
  INDEX `fk_measfiring_firing1_idx` (`firing_id` ASC) VISIBLE,
  CONSTRAINT `fk_consmeasure_measure1`
    FOREIGN KEY (`measure_id`)
    REFERENCES `mine_op`.`measure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measfiring_firing1`
    FOREIGN KEY (`firing_id`)
    REFERENCES `mine_op`.`firing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`brokenstock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`brokenstock` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Do we need to add a depletion id?',
  `date` DATETIME NOT NULL,
  `bcm` DECIMAL NOT NULL,
  `tonnes` DECIMAL NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comment` VARCHAR(45) NULL,
  `ounces` DECIMAL NOT NULL,
  `parcel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_brokenstock_parcel1_idx` (`parcel_id` ASC) VISIBLE,
  CONSTRAINT `fk_brokenstock_parcel1`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `mine_op`.`parcel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`stockpilebalance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`stockpilebalance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tonnes` DECIMAL NOT NULL,
  `adjtonnes` DECIMAL NOT NULL,
  `ounces` DECIMAL NOT NULL,
  `adjounces` DECIMAL NOT NULL,
  `grade` DECIMAL NOT NULL,
  `adjgrade` DECIMAL NOT NULL,
  `loadhaul_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stockpilebalance_loadhaul1_idx` (`loadhaul_id` ASC) VISIBLE,
  INDEX `fk_stockpilebalance_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_stockpilebalance_loadhaul1`
    FOREIGN KEY (`loadhaul_id`)
    REFERENCES `mine_op`.`loadhaul` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stockpilebalance_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`locationug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`locationug` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The material source locations by pit, stage, RL, blast, block, flitch.',
  `name` VARCHAR(45) NOT NULL,
  `loctype_id` INT NOT NULL,
  `detail1` VARCHAR(45) NOT NULL,
  `detail2` VARCHAR(45) NULL,
  `detail3` VARCHAR(45) NULL,
  `detail4` VARCHAR(45) NULL,
  `detail5` VARCHAR(45) NULL,
  `detail6` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`budget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `budget_col` VARCHAR(45) NOT NULL,
  `volume` DECIMAL NOT NULL,
  `tonnes` DECIMAL NOT NULL,
  `metal` DECIMAL NOT NULL,
  `drillm` DECIMAL NULL,
  `lhrate` DECIMAL NULL,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment` VARCHAR(45) NULL,
  `stockpile_id` INT NOT NULL,
  `locationop_id` INT NOT NULL,
  `oxidation_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_budget_stockpile1_idx` (`stockpile_id` ASC) VISIBLE,
  INDEX `fk_budget_locationop1_idx` (`locationop_id` ASC) VISIBLE,
  INDEX `fk_budget_oxidation1_idx` (`oxidation_id` ASC) VISIBLE,
  INDEX `fk_budget_material1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_budget_stockpile1`
    FOREIGN KEY (`stockpile_id`)
    REFERENCES `mine_op`.`stockpile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_budget_locationop1`
    FOREIGN KEY (`locationop_id`)
    REFERENCES `mine_op`.`locationop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_budget_oxidation1`
    FOREIGN KEY (`oxidation_id`)
    REFERENCES `mine_op`.`oxidation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_budget_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mine_op`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`planthour_has_loadhaul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`planthour_has_loadhaul` (
  `planthour_id` INT NOT NULL,
  `loadhaul_id` INT NOT NULL,
  PRIMARY KEY (`planthour_id`, `loadhaul_id`),
  INDEX `fk_planthour_has_loadhaul_loadhaul1_idx` (`loadhaul_id` ASC) VISIBLE,
  INDEX `fk_planthour_has_loadhaul_planthour1_idx` (`planthour_id` ASC) VISIBLE,
  CONSTRAINT `fk_planthour_has_loadhaul_planthour1`
    FOREIGN KEY (`planthour_id`)
    REFERENCES `mine_op`.`planthour` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planthour_has_loadhaul_loadhaul1`
    FOREIGN KEY (`loadhaul_id`)
    REFERENCES `mine_op`.`loadhaul` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_op`.`truckfactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_op`.`truckfactor` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Types of activities: load and haul, drilling, blasting.',
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `factor` DECIMAL NOT NULL,
  `planttype_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_truckfactor_planttype1_idx` (`planttype_id` ASC) VISIBLE,
  CONSTRAINT `fk_truckfactor_planttype1`
    FOREIGN KEY (`planttype_id`)
    REFERENCES `mine_op`.`planttype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
